### ISSUE TITLE
Focus not set after item is selected

### ISSUE THREAD

**Issue by andrei-datcu** [downshift-js/downshift#1014]
- `downshift` version: 5.2.0

**Relevant code or config**

Taken the official examples:
https://codesandbox.io/s/usecombobox-usage-evufg  (usecombobox)
https://codesandbox.io/s/simple-downshift-with-getrootprops-example-24s13 (`<Downshift/>`)

**What you did**:
Click the input. Start typing and select an option using your mouse / enter key. Alternatively, you could use the drop button.

**What happened**:
The focus went nowhere

**Problem description**:
Shouldn't the focus move back to the trigger (either the input or the button)? This is what the documentation states and this is how the examples on the docs page do, but this is not what the component is doing in the latest version.

**Comment by silviuaavram** [comment]
I checked both the sandboxes (5.1.1) and the docsite examples (5.2.0) and they behave the same. Correct me if I'm wrong.

When using mouse, keyboard focus means nothing. You will be using mouse, why should we manage your focus and presume that you will switch to keyboard at any point? You are done with the selection, you did it with mouse, how am I supposed to know where are you going to navigate next? With the mouse, your next interaction can be anywhere.

When using keyboard that is different. And if you select item by keyboard Enter, you will see focus stays in the input. You are done with the selection, but since you are using keyboard, then focus has no reason to leave the input, as you need to continue your navigation via (Shift)Tab.

There is an exception. When you open list with toggle button click, since the widget has more functionality exposed via keyboard that is not possible with mouse (input change) then we will manage the focus for you, and after click, we will put focus on the input.

https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html more details on these examples and in the linked listbox pattern on that page. However this question is also about general focus handling in an app.

**Comment by andrei-datcu** [comment]
> 
> 
> I checked both the sandboxes (5.1.1) and the docsite examples (5.2.0) and they behave the same. Correct me if I'm wrong.

Not for me. Here's a gif when I'm using the mouse to select the option on the documentation site:
![focus](https://user-images.githubusercontent.com/7924441/80280188-3f067800-870b-11ea-880e-716caabf6d4f.gif)


> When using mouse, keyboard focus means nothing. You will be using mouse, why should we manage your focus and presume that you will switch to keyboard at any point? You are done with the selection, you did it with mouse, how am I supposed to know where are you going to navigate next? With the mouse, your next interaction can be anywhere.

I agree this is totally debatable and you have way more knowledge in that area than I do :)
However, I'm thinking about Windows / Cocoa combos and there the focus is handled after you select your option with the mouse: On Windows, the focus stays on the input, on Mac the focus moves to the next control in tab order.

Furthermore, citing from the `useComobox` README:

>Item
> Click: It will select the item, close the menu and move focus to the toggle button (unless defaultIsOpen is true).

So yeah, not on the input, but not on the body either.

If you need more insights about my usecase:
I am using `useCombobox` together with `useMultipleSelection` and I was expecting the focus to remain on the input after my first selection to easily accommodate further selections the user might be doing. I agree this is only applicable for multiple selection and I already have all the tools needed to set the focus myself. I just wanted to point out what I deem to be a small inconsistency :)

**Comment by leoweigand** [comment]
> When using mouse, keyboard focus means nothing. You will be using mouse, why should we manage your focus and presume that you will switch to keyboard at any point?

@andrei-datcu has a point–I would argue that downshift’s default behaviour should work the same way `<datalist>` does, as that is the standard pattern provided by browsers. Check out [this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) from MDN, focus on the input field is retained both when selecting a suggestion by keyboard or mouse.
