### ISSUE TITLE
onFocus race condition with useCombobox.stateChangeTypes.ToggleButtonClick

### ISSUE THREAD

**Issue by tommedema** [downshift-js/downshift#1095]
As per #504 we've added an onFocus listener to be able open the menu when the user focuses the input. At the same time, if the menu is already opened and the user clicks on the ToggleButton, we need to close the menu again.

The problem is that if the input is not focused and the user clicks on the ToggleButton to focus the input, our onFocus listener will open the menu, and then after that the useCombobox.stateChangeTypes.ToggleButtonClick state change is triggered, which would cause our app the close the menu again.

- `downshift` version: 5.4.5
- `node` version: N/A, this is in browser
- `npm` (or `yarn`) version: yarn 1.17.3

**Relevant code or config**

Our listeners:

```javascript
 // inside the state change callback
        case useCombobox.stateChangeTypes.ToggleButtonClick:
          if (!isOpen) {
            openMenu()
          }
          else {
            closeMenu()
          }
          break

// the input focus callback
  const onInputFocus = useCallback(() => {
    if (!isOpen) {
      openMenu()
    }
  }, [])
```

Our input:

```javascript
            <Input
              {...getInputProps({
                ...getDropdownProps({
                  preventKeyAction: isOpen,
                  ref: inputRef,
                }),
                onKeyDown,
                placeholder,
              })}
              onFocus={onInputFocus}
            />
```

How can we avoid closing the menu due to onInputFocus and ToggleButtonClick firing sequentially, the first opening the menu, and the second closing it again? We only want  ToggleButtonClick to close the menu if it was not that click that first focused the input.

**Comment by silviuaavram** [comment]
Hi, isn't [this example](https://www.downshift-js.com/use-combobox#using-action-props) the case that you actually want?

**Comment by tommedema** [comment]
No, that doesn't open the combobox on focus.

**Comment by silviuaavram** [comment]
It does
```js
          <input
            {...getInputProps({
              onFocus: () => {
                openMenu()
              },
            })}
          />
```

**Comment by tommedema** [comment]
@silviuaavram sorry I just edited my response

**Comment by tommedema** [comment]
@silviuaavram I think this reproduces the issue:

https://codesandbox.io/s/usecombobox-action-props-z6qkg?file=/src/index.js

Try focusing the input by clicking on it with your mouse, it'll close it again immediately.

**Comment by silviuaavram** [comment]
Last resort https://codesandbox.io/s/usecombobox-action-props-5915u

But maybe you can figure a better solution.

**Comment by tommedema** [comment]
@silviuaavram i'm ok with that but it has a bug: when you open the input by focusing it with a "tab" keypress, and then click on the input, it won't disappear

see https://app.usebubbles.com/t4QVbP7D3WJWiZFkYphE3z/comments-on-codesandbox-io

**Comment by constantinpojoga** [comment]
@tommedema Same here: https://github.com/downshift-js/downshift/issues/504#issuecomment-672262676. The way it worked for me:
```
onFocus: e => {
    if (!isOpen) {
      openMenu();
    }
},
```

**Comment by constantinpojoga** [comment]
@silviuaavram I noticed a race condition for the `onBlur` event too. Steps to reproduce:
- focus the input field, and open the menu. In my case, the menu is opening on blur
- while using the keyboard or hovering the menu options, the input field will hold the focus as expected
- when selecting an option, `onBlur` will fire, and right after that, the input field will get another `onFocus` (the issue from the previous comments).

In my case, I'm showing a validation error for required fields, only after the input was blurred at least one time, and because onBlur fires faster than onSelectedItemChange, I can see the validation error for a split second.
Wanted to ask if there is any way to prevent `onBlur` (same for `onFocus`)  on option-click?

**Comment by silviuaavram** [comment]
Maybe `what-input` ? https://github.com/ten1seven/what-input

I can't think of anything. Maybe `targetWithinDownshift` function from our utils can help, since it tracks if the event target is within the downshift elements (menu, input).
https://github.com/downshift-js/downshift/blob/23f37157dbd4f27433ac92406b7089c15d056bcd/src/utils.js#L413

**Comment by constantinpojoga** [comment]
Not sure if I made clear the issue: when focusing the input, the first `onFocus` triggers as expected. The issue comes when trying to click an option. At this point, `onBlur` is triggered + another `onFocus`. All 3 events have the exact same `event.target`, the input field.
`targetWithinDownshift` can be useful to detect if the new element is withing Downshift, instead of the className hack. It would be really helpful to detect if the newly focused element is the adjacent expand button, so it would prevent onBlur in this case. 
Still will have to use the setTimeout to test the new document.activeElement. 
My question was if there is you can think of any way to stop the `onBlur + `onFocus` on option-click from the library? This would solve this, the `openMenu` and similar issues.

**Comment by silviuaavram** [comment]
I see. Well, the handlers execute as expected.

Maybe there is another way to achieve what you want? Instead of using event handlers.

I lost track of the discussion. Can you start with an example from the docsite and describe what you want to achieve in addition?

**Comment by mayteio** [comment]
Sorry to revive this, but the (similar) problem we're facing is we want the dropdown to open on first focus. We do this via `getInputProps({ onFocus: () => openMenu() })`.

When an item is selected though, the input is focussed again, thus calling the `onFocus` again (as expected). The order the handlers are called though, `selectedItem` is updated **after** onFocus, so there's no way to check whether `inputValue` matches the selection to keep it closed, i.e. 

```
onFocus: () => {
  if(inputValue === ""){
    openMenu()
  }
}
```

**Comment by IanVS** [comment]
I was just hit by this as well, and determined that it started in version 5.4.5.  

It can be reproduced in https://codesandbox.io/s/downshift-issue-1095-qp3st.  Click the input, click an option, and notice that the menu stays open.  If you change the version of downshift to 5.4.4, and repeat, the menu will close.

**Comment by imabp** [comment]
Hey if anyone is still facing this, issue.
I did a light hack over this stuff, without involving the complexity of state reducer.
I was using Chakra-UI, Box and Input are the components from Chakra-UI

```tsx
<Box
position="relative"
onClick={()=>{isOpen ? closeMenu(): openMenu()}
>
<Input
 {...getInputProps(
 {
     onFocus: ()=>{
      if(!isOpen)
          openMenu();
     }
 })}
 />
</Box>
```

To overlap the styles of Box and Inputs visually, 
you have to do accordingly style out these properties of box
`border:none`, and `&:focus:none`
