### ISSUE TITLE
[useSelect] RefObjects for menu sub-component has a side effect when used with react-popper library

### ISSUE THREAD

**Issue by oageyeva** [downshift-js/downshift#1096]
- `downshift` version: 5.4.2
- `node` version: 12.18.1
- `npm` (or `yarn`) version: 6.14.4

**Relevant code or config**

```
const menuRef = useRef(null);


  <Downshift item={items}>
     <ul {...getMenuProps({ ref: menuRef })}>{children} </ul>
  </Downshift>
 ```
or
```
<Downshift item={items}>
     <ul {...getMenuProps({ ref: e=>menuRef.current=e })}>{children} </ul>
  </Downshift>
```

**What you did**:
I am trying to integrate popper.js with downshift dropdown. I used useSelect and usePopper hooks for my implementation. 

**What happened**:
I see this downshift error
![image](https://user-images.githubusercontent.com/62906145/85245009-4b116c00-b414-11ea-9dcf-657d2f4bd09d.png)

Besides that all works as expected.

**Reproduction repository**:
[Sandbox code](https://codesandbox.io/s/dropdown-with-downshift-and-built-in-popper-nq6by?file=/src/Components/Dropdown/dropdown-menu/dropdown-menu.js)

**Problem description**:
I found similar discussions [here](https://github.com/downshift-js/downshift/issues/713) and there seems to be a fix for that ([here](https://github.com/downshift-js/downshift/pull/775) and [here](https://github.com/downshift-js/downshift/pull/813)), but for some reason it still not working for me. 
I tried recommended callback solution - it did not work for me either. 

Steps to recreate the issue:
1. [In the sandbox in dropdown-menu file](https://codesandbox.io/s/dropdown-with-downshift-and-built-in-popper-nq6by?file=/src/Components/Dropdown/dropdown-menu/dropdown-menu.js) remove line 23. `ref={e => (menuRef.current = e)} ` Now ref is being passed in to getMenuProps 
2. Scroll to find a toggle button in a browser window. Click on toggle button to open a menu.
3. If it opens down, close menu and move toggle button close to the bottom edge and click again.
4. The parent window scrolls up when menu open. This is incorrect behavior - the menu supposed to open up, not down and no parent scrolling should be happening.
5. If the menu in step 3 opens up, move it close to top to see the same effect.

6. In dropdown-menu file put line 23 back.
7. Try steps above to see a different behavior. 
8. Moving ref before getMenuProps seems to have the same side effect:
```
 <ul
      ref={e => (menuRef.current = e)}
      {...getMenuProps(
        { ...popperAttributes, style, ref: e => (menuRef.current = e) },
        { suppressRefError: true }
      )}      
    >
```

**Suggested solution**:
Not sure. Maybe the fix mentioned above is not accessible through useSelect? Or maybe ref is being applied too soon before the menu opens and this affects popper positioning behavior.

**Comment by silviuaavram** [comment]
Hi! You don't need any ref magic in this case, since you have `<ul>` and not a custom component. So don't bother with passing any ref to `useSelect`.
Scrolling happens because when the dropdown is open, the menu is focused. Which means that, if you use popper and your menu is on the end of the DOM and the page is scrollable, then it scrolls. 
Similar: https://github.com/downshift-js/downshift/issues/899

**Comment by oageyeva** [comment]
@silviuaavram Thanks for explanation! In issue [#899](https://github.com/downshift-js/downshift/issues/899) you recommend fixing it with css or creating a portal and advise against experimenting with menu focus.  Could you please give me a bit more details on how this could be possibly fixed with css?

**Comment by silviuaavram** [comment]
It means ditching any popper/portal and position your list using only CSS. That way, since the list is close to the toggle button in the DOM, and not at the end (in the case of portal/popper) there won't be any scroll.

If your use case doesn't need any popper/portal then you should try css positioning. Otherwise use the hook in a page without any scroll.

I have no idea how to fix this case, since we need the focus to go on the menu in order to make the `<select>` accessible.
