### ISSUE TITLE
Downshift component: Home & End do not move a cursor on `input`

### ISSUE THREAD

**Issue by layershifter** [downshift-js/downshift#1097]
- `downshift` version: 5.4.5
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

**Relevant code or config**

Default example on https://www.downshift-js.com/downshift.

**What you did**:

1. Jump to an example on https://www.downshift-js.com/downshift
2. Write "Foo" to an input
3. Press `Home` hey

![downshift-keys](https://user-images.githubusercontent.com/14183168/85709172-49ca9280-b6e5-11ea-81e6-d480d5064c5b.gif)

**What happened**:

Cursor stays at the end of string, but on inputs it should be moved to start.

**Reproduction repository**: N/A
**Problem description**: N/A
**Suggested solution**: N/A

**Comment by silviuaavram** [comment]
I guess this is a matter of preference, since in the case of the combobox, ARIA suggests either focusing first/last element (downshift default) or moving cursor to the end/start (your scenario). When we built the `Dropdown` for Stardust, the element focus with Home/End was a hard requirement, so we went for this approach and also adopted it in Downshift.

You can prevent the default behavior by using [event.preventDownshiftDefault](https://github.com/downshift-js/downshift#customizing-handlers). Just make sure you stop the scrolling if you choose to go ahead with this.

**Comment by silviuaavram** [comment]
To be fixed by only calling `event.preventDefault` and `dispatch` if `isOpen` is true. I think we should also review the other handlers and do the same where applicable.

**Comment by joaopaulobdac** [comment]
The way I chose to approach this in my project is to `preventDownshiftDefault` if `highlightedIndex` is `-1`. This way, the home/end keys only change behavior to interact with the list when the user starts navigating the list using the arrow keys. I think this feels very natural.

**Comment by silviuaavram** [comment]
@joaopaulobdac that's one way to do it. I am not 100% sure about it though, since when you open the menu, you can't just go to the last option without doing an arrow up/down first.

Will start working on a fix for this as described in my previous comment.
