### ISSUE TITLE
Input Loses Focus in MultipleSelection

### ISSUE THREAD

**Issue by joe-bell** [downshift-js/downshift#1187]
- `downshift` version: 6.0.6
- `node` version: 
- `npm` (or `yarn`) version:

**Relevant code or config**

See repro

**What you did**:

First of all **thank you so much for this library**, it's really helped get my up to speed with custom comboboxes etc. 
Unfortunately I've been battling with maintaining my text input's focus state after an item is selected.

I followed the docs example, but was unable to recreate the same behaviour with my implementation. I tried setting a custom ref, messing around with state reducer (where I felt out of my depth) but ultimately feel like I'm going in circles here.

**What happened** / **Problem description**:

When an item is added, the text input loses focus (the style is maintained due to `useState` - for a use-case style which `:focus-within` couldn't quite offer). Note that the text input's cursor stops blinking once an item is selected

**Reproduction repository**:

> Disclaimer: this code is truly disgusting, I'm sorry (I had to strip out a lot of private content)

https://codesandbox.io/s/downshift-1187-repro-e416f

**Suggested solution**:

I'm guessing I've probably missed something here or it's down to my implementation. I would really appreciate any help to get it resolved 🙏🏼

**Comment by joe-bell** [comment]
Hi @silviuaavram thanks so much for this

I've added a default switch case but please could you specify what you mean with `ref` in a code example?   
I'm not entirely sure what you mean and I'm still a bit stuck

New Codesandbox: https://codesandbox.io/s/downshift-1187-repro-with-suggested-repairs-vvqon

**Comment by silviuaavram** [comment]
Sure. Just remove `refKey: 'innerRef'` and it will work.
If you check the ChakraUI Input props, you will not see any innerRef prop, but `ref`. Downshift also uses `ref` as prop name by default, so no need for you to specify another `refKey`.

This is useful as both downshift and Input require the ref for the input html element. Since downshift will end up dumping props on the Input, knowing what's the custom component's prop for the ref is important. You can check our code for `[refKey]: handleRefs` and see how we are handling this case.

Something wrong in your example: when you select an item, the focus jumps from the Input to some Chakra container. This must not happen, after selection input should still be focused, so you can keep what you are doing.

Let me know how it goes.

**Comment by joe-bell** [comment]
Thanks, I've tried removing `refKey: 'innerRef'` but sadly still not much luck

>Something wrong in your example: when you select an item, the focus jumps from the Input to some Chakra container. This must not happen, after selection input should still be focused, so you can keep what you are doing.

Sorry perhaps I wasn't clear enough in the issue, **this** is what I'm stuck with and I can't for the life of me figure out how to get the focus maintained on the input. Do you have any idea what could be happening here to prevent the input losing focus? This is the problem that lead me to opening this issue

See https://codesandbox.io/s/downshift-1187-repro-with-suggested-repairs-vvqon

**Comment by joe-bell** [comment]
@silviuaavram as a follow up, I tried replacing Chakra UI with plain HTML and this issue still persists (so I've renamed the issue)

Please could you suggest how I prevent the input losing focus here?

**Comment by silviuaavram** [comment]
@joe-bell your `Wrap` seems to be the issue. Once you add another element to the selection, it will rerender everything again.

The problem is that it considers every node to be an `<li>` be it selected item or the combobox input. So on rerender, it will re-create the `<li>` with the combobox. Since the old `<li>` node is discarded, the ref to the input in useCombbox is going to be null => focus is lost to the body.

Makes sense? I don't know what to suggest as a fix, it's related to Chakra so you may need to figure it out. But once you're done the whole components looks great! Please consider creating PRs to add it as a usage example to both downshift-examples and downshift-docs. I will guide you further if needed. Thank you!

**Comment by joe-bell** [comment]
Right that makes a lot of sense! I've been so tunnel-visioned on `ref` that I completely missed the fact `Wrap` is probably running a `React.Children` map function. Thanks so much for your patience and taking the time to look into this for me, I really appreciate it

I'll close this as I think it's fair to say it's unrelated to Downshift
