### ISSUE TITLE
Multiple ids for aria-labelledby

### ISSUE THREAD

**Issue by kserjey** [downshift-js/downshift#1192]
- `downshift` version: 3.2.10
- `node` version: 14.6.0
- `yarn` version: 1.22.4

**Relevant code or config**

Bare-bones example of what I have:

```jsx
<h3 id='inputs-heading'>My great inputs</h3>
<div>
  <label id='input1-label'>My textinput</label>
  <input aria-labelledby='inputs-heading input1-label'/>
</div>
<Downshift inputId='input-heading input2-label'>
  {() => (
    <div>
      <input {...getInputProps()}/>
    </div>
  )}
</Downshift>
```

**Problem description**:

There is no way to have multiple label ids in `aria-labelledby` if you have `getLabelProps`. In my case I don't have any label element, so I just pass multiple ids to `labelId` prop, but I have checked source code of Downshift and found that it would be a problem with `getLabelProps`:

https://github.com/downshift-js/downshift/blob/f4cb1779fdca7973276cd2b5f217203e3b1c0c25/src/downshift.js#L755-L757

It injects `id` to label element, so if someone change my implementation in our codebase with `getLabelProps`, it breaks. Of course we could override `id`, but I think it's not ordinary and I can't warn a developer to do it.

Also I realized that `this.getLabelProps.called` is never changed:

https://github.com/downshift-js/downshift/blob/f4cb1779fdca7973276cd2b5f217203e3b1c0c25/src/downshift.js#L1187-L1188

**Suggested solution**:

I was thinking about using an array of ids, but we should somehow determine one id for label element.

**Comment by silviuaavram** [comment]
Hi! Thanks for posting this.

To me `inputId='input-heading input2-label'` does not make a lot of sense. The id of an element should be unique.

Our whole `getLabelProps` philosophy requires you to have an actual label, and I personally always try to enforce this. Yes, the design sometimes is without a physical label, and aria-label or aria-labelledby is used.

Since this is you case I would probably suggest to ditch anything provided by downshift and just use an `aria-label` or `aria-labelledby` property passed directly to `getInputProps` (probably also to getMenuProps I don't remember), since you don't need Downshift's help here anyway.

What do you think?

**Comment by silviuaavram** [comment]
Also @kserjey consider moving to `useCombobox`!

**Comment by kserjey** [comment]
Yeah, recently we have moved to Downshift hooks in our projects. It feels better! 
Maybe you are right and we should make it work ourselves. Of course passing multiple ids to `inputId` is bad overall, but it was a quick solution to get it done. If someday this feature will be available as build-in, it would be good. Thanks!
