### ISSUE TITLE
[useCombobox] InputKeyDownEnter action not triggering when focus is on the input field on version 6.1.0

### ISSUE THREAD

**Issue by lasota-piotr** [downshift-js/downshift#1234]
- `downshift` version: `6.1.0`

- `node` version: `14.2.0`
- `yarn` version: `1.22.10`

**Relevant code or config**

```javascript
function stateReducer(state, actionAndChanges) {
    const { type, changes } = actionAndChanges;
    // Doesn't log when a user has focused on the input and pressed enter
    console.log(actionAndChanges);
    return changes;
  }
```

**What you did**:
1. I clicked on the input and typed `hi`
2. I pressed `enter`

**What happened**:
It didn't log `actionAndChanges` variable

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-inputkeydownenter-action-not-triggering-when-focus-is-on-the-input-field-lrtmr?file=/src/App.js

**Problem description**:
The problem is the same as here https://github.com/downshift-js/downshift/issues/1114 but on version `6.1.0`. On  version `6.0.4` works correctly.

**Comment by silviuaavram** [comment]
Should the state of the component change once you pass enter? If not, then stateReducer should not get called. Before https://github.com/downshift-js/downshift/pull/1218 it was broken, that's why you got that called.

https://github.com/downshift-js/downshift#statereducer

If you need to execute your own logic independent from downshift then use your own event handlers.
