### ISSUE TITLE
Remove error message:  ref prop "ref" from getMenuProps was not applied correctly on your menu element

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [downshift-js/downshift#1272]
- `downshift` version: 6.1.2
- `node` version:16.1.0
- `npm` version: 7.12.0

**Relevant code or config**

```javascript
<ul
{...getMenuProps()}
className="..."
>
{filteredSuggestions.map((o, i) => {
  return (
    <li
      key={i}
      onClick={() => {
        selectItem(o);
      }}
      className={`${
        highlightedIndex === i
          ? 'bg-blueGray-600 text-lightBlue-100'
          : ''
      } flex items-center justify-between py-1 pl-4 my-1 hover:cursor-default`}
      {...getItemProps({ item: o, index: i, key: o.w })}
    >
      <HighlightSubstring
        inputValue={inputValue}
        suggestion={o.w}
      />
    </li>
  );
})}
</ul>
```

**What happened**:
it works fine but the console error does not go away

**Reproduction repository**
[repo: ](https://github.com/Ali-Hussein-dev/find-meaning/blob/master/src/components/SearchBar.tsx)

**Problem description**:
I am using downshift in a dictionary project for auto-complete.
error message in development env: 
downshift: The ref prop "ref" from getMenuProps was not applied correctly on your menu element.

[see error](https://drive.google.com/file/d/1Tsy64q_FmVrkOCxrfxhgEGPxXHCHaqrY/view?usp=sharing)

**Comment by gperl27** [comment]
I'm seeing this error in a situation where I have a popover node that uses a portal to hide/show the list elements. You can silence the error using the second options argument and the prop `suppressRefError`:

```
<ul {...getMenuProps({}, { suppressRefError: true })} />
```

Though the docs do explicitly warn against this, the functionality seems to work as expected as you mention. In my case, I am completely mounting and unmounting the menu node. (I'm also using a `ul` that has a styled components wrapper, which auto forwards the ref, so things seem fine on the `ref`'ing end too).

As to why this is happening, the source code basically checks if `getMenuProps` was called and that there is an existing menu node in existence:

```
componentDidMount() {
    /* istanbul ignore if (react-native) */
    if (
      process.env.NODE_ENV !== 'production' &&
      !isReactNative &&
      this.getMenuProps.called &&
      !this.getMenuProps.suppressRefError
    ) {
      validateGetMenuPropsCalledCorrectly(this._menuNode, this.getMenuProps)
    }

   /* rest componentDidMount impl */
}
```

Thus, it makes sense if this happening to you if you are completely mounting/unmounting the menu like I am.

**Comment by osdiab** [comment]
I am in the same boat as @gperl27 - is there any actual issue if the menu just isn't rendered at all until interaction? I use a popover with `@tippyjs/react` to render the menu, and its behavior is that if the popover isn't visible, then it just doesn't render the menu at all. This causes the ref error to occur, since indeed the ref isn't set—shouldn't the ref only really matter if the downshift state is that the menu is open? cc @kentcdodds would love some feedback here!

**Comment by vctormb** [comment]
I'm having the exactly same problem. I'm mounting and unmounting the Menu component and getting a lot of errors

**Comment by silviuaavram** [comment]
As indicated in the [docs](https://github.com/downshift-js/downshift#getmenuprops) and in the [ARIA page](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html), the menu needs to stay in the DOM at all times. Do not remove it.

You have 2 options: conditionally render the menu items when `isOpen` is `true`, or have everything rendered, just add `display: none` when `isOpen` is `false`.

**Comment by silviuaavram** [comment]
As for the first example in this issue, with that exact code, there should be no such error.

**Comment by silviuaavram** [comment]
Check the examples on https://www.downshift-js.com/ and their associated code sandboxes for the markup.

**Comment by montoriusz** [comment]
@silviuaavram

> You have 2 options: conditionally render the menu items when isOpen is true, or have everything rendered, just add display: none when isOpen is false.

Hi, I think you missed one crucial thing which is the menu being rendered in a portal. Portal* defers rendering of its contents because it creates container node in effect and the contents comes in on next render. In such case, which I believe is common,  there's no chance that the menu renders in sync with getMenuProps call.

I think that ref check could be deferred "to the next effect" and support this case while still doing its job.

* - I mean Portal implementations (e.g. Chakra-UI) that work with SSR without complex techniques like react-portal-universal.

**Comment by silviuaavram** [comment]
I cannot predict all libraries that are going to be used along with downshift. Consequently, if you cannot use the markup that we suggest for whatever reason, feel free to use `suppressRefError` and do whatever works for you.

Not sure if there is anything to fix on this side.

**Comment by montoriusz** [comment]
@silviuaavram Thanks for your response.
Yeah, there is nothing to be fixed in a strict sense. It is a suggestion to make this ref check more helpful in real-world cases. What makes portal component in different libraries (MUI, Chakra) behave this way is not the particular implementation but rather making it flexible while following React best practices.

**Comment by vctormb** [comment]
> @silviuaavram Thanks for your response. Yeah, there is nothing to be fixed in a strict sense. It is a suggestion to make this ref check more helpful in real-world cases. What makes portal component in different libraries (MUI, Chakra) behave this way is not the particular implementation but rather making it flexible while following React best practices.

[Floating UI](https://floating-ui.com/docs/interactions-examples) has a lot of examples on how to build dropdown components with a11y support. It's really nice!
