### ISSUE TITLE
useSelect With Nested Checkboxes, Parent is Always the selectedItem

### ISSUE THREAD

**Issue by wluisi** [downshift-js/downshift#1290]
- `downshift` version: 6.1.3
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Problem description**:
I'm trying to create a MutliSelect component using downshift's `useSelect` hook, that allows for nested checkboxes. I'm having an issue where the parent checkbox is always the `selectedItem`, not the child checkbox.

Are nested checkboxes something downshift supports? If so, what's the best way to do this?

**Reproduction repository**:
Example of the problem is here in this simple code sandbox:
https://codesandbox.io/s/downshift-multiselect-nested-checkboxes-8448y?file=/src/MultiSelect.js

**What you did**:
One workaround that sort of works is doing an `onChange` on the child checkbox input with the `selectItem` action:
```
onChange={() => {
  selectItem(childItem);
}}
```
See full example here: https://codesandbox.io/s/downshift-multiselect-nested-checkboxes-8448y?file=/src/MultiSelect.js

**What happened**:
Doesn't seem like a good approach to solve the issue, as it only works for checkbox, label does not trigger a change.

**Comment by silviuaavram** [comment]
Hi @wluisi ! Do you really need the nested markup? I am not sure about having such complex markup in a listbox.

What about just having all options as `<li>` elements and style them according to your nested structure?

**Comment by florianchevallier** [comment]
Hi @wluisi, I'm facing the exact same issue here. 

Did you manage to solve it ?

@silviuaavram, I tried also your solution (juste having lis) and it doesnt work on my side.

Here is the codesandbox example : https://codesandbox.io/p/github/codesandbox/codesandbox-template-vite-react/csb-hlev8z/draft/cool-frost?file=/src/TreeSelect.tsx:2,23

**Comment by silviuaavram** [comment]
@florianchevallier I think the `useCombobox` needs to know about all the items. Right now, you are passing only the countries, it does not know that there are children as well.

Maybe create a flatItems array and use that? `const flatItems = items.reduce((acc, item) => [...acc, item, ...item.children], [])` and pass `flatItems` to useCombobox: `const returns = useCombobox({items: flatItems})`

And make sure to have the correct index in each getItemProps, right now the child one is incorrect. Maybe just remove it, since if you pass the flatItems to useCombobox and item in each getItemProps call, downshift will know how to get the index via reference search.

Let me know if it works like this. It worked for me in your example.
