### ISSUE TITLE
items not getting highlighted if getItemProps is used at multiple places

### ISSUE THREAD

**Issue by ashwinkhode** [downshift-js/downshift#1371]
- `downshift` version: 6.1.7
- `node` version: 16.13.2
- `npm` (or `yarn`) version: 8.1.2

**What you did**:
I used getItemProps at two different places. I am rendering two arrays : 
1) filtered countries based on inputValue 
2) all the countries from rawCountries data which are imported from `countries.js`. 

To reproduce the behavior: 
1) Click input element and type `india`
2) Press Up and Down keys to highlight the filtered countries

I want to highlight through both countries list (filtered countries and all countries) when pressed up/down arrow keys but I can only highlight filtered countries when inputValue is not empty. Please correct me what I am doing wrong. Using getItemProps at two places is probably what I am doing wrong but how would I get the desired behaviour? 🤔  

**What happened**:
I should be able to highlight all the countries along with filtered countries list but not able to do it with arrow up/down keys.

**SCREENSHOTS**:
![image](https://user-images.githubusercontent.com/53361996/161585453-77f81ce3-2cb8-4574-8149-2dbbf1e95ced.png)
![image](https://user-images.githubusercontent.com/53361996/161585488-d71c3845-c012-4dca-84e3-96e108b68d0f.png)

**Reproduction repository**:
https://2sizxc.csb.app/

**Comment by silviuaavram** [comment]
Hi!

`getItemProps` should be called on each element in the list, with the correct item and index.

As such, your second list should probably have this call `{...getItemProps({ country, index: filteredCountryListLength + index })}`, as it comes after the first filtered items list, but you want to treat everything as one list.

Furthermore, your `items` argument is actually `items: [...filteredCountryList, ...rawCountries],`, since that's what actually happening.

There is still one more issue with your code, which I didn't figure out, but hopefully you do and fix it. Let me know in the comments what it was, so we can have this fixed in case someone else encounters a similar problem. Thanks!

**Comment by ashwinkhode** [comment]
Thank you so much @silviuaavram ❤️ 

You are actually 5HEAD it works now as expected. I didnt find any other issue as you mentioned but I will update it here if I find any.
