### ISSUE TITLE
Different effects about clicking inside downshift element in mobile/tablet and desktop

### ISSUE THREAD

**Issue by pudgecit** [downshift-js/downshift#1395]
- `downshift` version: 6.1.7
- `node` version: v16.13.0
- `npm` (or `yarn`) version: 8.1.0

**Relevant code or config**

```javascript
```

**What you did**:
I create a simple downshift usage.

**What happened**:
I find there has a different effects in desktop and mobile/tablet, when I was clicking some element inside downshift children.

**Reproduction repository**:
https://github.com/pudgecit/test-downshift

Codesandbox: https://codesandbox.io/s/inspiring-oskar-18ts09?file=/src/App.js
or use this https://18ts09.csb.app/ (please toggle into mobile or tablet and PC to see differences)

**Problem description**:
I want to make sure that when I was clicking some elements inside downshift, the autocomplete menu will still be visible, and only if I click outside downshift container, then the menu could be hidden.
But I found that it works well in the desktop, but when I switched into mobile or tablet by using chrome device tool, when I was clicking the same elements, then the menu was closed.
so I want to ask for some help is there a way to keep the same effect on desktop and mobile/tablet.
![pc-demo](https://user-images.githubusercontent.com/101076268/182096831-bad36dff-5bee-4d24-9b70-cd0b966035d0.gif)

![mobile-demo](https://user-images.githubusercontent.com/101076268/182097072-8955fd27-4a1d-4228-8329-ff8484db059d.gif)

**Suggested solution**:
maybe I misunderstand somethings, but I am going to implement a feature that want to do some "click" inside downshift and keep the menu always visible, so I am a little confused why the behavior is different in PC and mobile/tablet

**Comment by silviuaavram** [comment]
No idea why and probably will not fix anything for the following reasons:
1. Downshift is not going to receive any updates, as we use `useCombobox` instead moving forward. You should too!
2. The combobox markup is input, toggle (optional) and menu with items. Everything else is not correct and if you choose to do it, you handle it yourself.

I'd rather add actionable elements outside the combobox markup. And switch to useCombobox, since we plan to deprecate Downshift as a component.
