### ISSUE TITLE
getToggleButtonProps is setting tabIndex of trigger to -1 and making it inaccessible

### ISSUE THREAD

**Issue by raza-jamil-reckon** [downshift-js/downshift#1400]
- `downshift` version: 6.0.6
- `node` version: 12.22.1
- `pnpm` version: 5.18.9

**Relevant code or config**

```javascript
  const {
    getToggleButtonProps,
  } = useCombobox({ ... });

return <><button {...getToggleButtonProps()}/></>
```

**What you did**: Use the `useCombobox` hook to get props for my trigger button using `getToggleButtonProps`.

**What happened**: The trigger button is inaccessible. 

**Reproduction repository**: Repro can be observed in the docs site and screenshots below.

**Problem description**:

This is also the case on the docs website. When using the hook version, the trigger is inaccessible but when using the component version the trigger does not have `tabIndex = -1`. See snaps below:

Notice `tabIndex = -1` when using the hook:
![Screen Shot 2022-08-19 at 9 42 46 am](https://user-images.githubusercontent.com/97567784/185513714-ffe09cbc-f756-46bb-968e-8bbce12bb2de.png)

Notice no `tabIndex = -1` when using the component:
![Screen Shot 2022-08-19 at 9 43 17 am](https://user-images.githubusercontent.com/97567784/185513753-ff01cf41-05c1-40e7-88c6-7c440c69bcd2.png)

**Suggested solution**:

I'm not sure why the trigger would have a negative tab index. I've fixed this temporarily by passing `tabIndex = 0` in my app. Would like some clarification, not sure if I'm missing something.

**Comment by silviuaavram** [comment]
Of course. https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html

So, the actual reason why there is a -1 value for the tabindex is to remove the toggle button from the tab order. We consider that leaving it in the tab order is unnecessary, since you can open or close the menu already with keyboard (arrow up, arrow down, escape, tab).

The reason why such a button even exists in the combobox markup is to allow opening the menu with mouse click, for users that focus on using the mouse.

Your override of tabindex with the 0 value is fine, as long as it's what you want and understand why we (and ARIA) suggested by default to have -1 on it.

Hope it helps. Thanks!

**Comment by raza-jamil-reckon** [comment]
That makes sense, thanks!
