### ISSUE TITLE
useSelect, `openMenu` when getToggleButtonProps is focused didn't work as expected

### ISSUE THREAD

**Issue by bryantobing12** [downshift-js/downshift#1432]
- `downshift` version: ^7.0.1
- `node` version: v16.14.2
- `npm` (or `yarn`) version: 7.17.0
- `react` version: 18.2.0

**Relevant code or config**

```typescript
<div
  className="p-2 bg-white flex justify-between cursor-pointer"
  // the only thing that i modified from basic example is adding openMenu when onFocus event called
  {...getToggleButtonProps({ onFocus: openMenu })}
>
  <span>{selectedItem ? selectedItem.title : 'Elements'}</span>
  <span className="px-2">{isOpen ? <>&#8593;</> : <>&#8595;</>}</span>
</div>
```

**What you did**:

I try to make the select component menu is open when the toggle button is focused

**What happened**:

I try to navigate with `tab` key, It indeed opens the menu when the toggle button is focused,
but when I try to access or open the menu using click event/ mouse. the first time i click the toggle button it's opening the menu and then immediately closing it

**Reproduction repository**:

https://stackblitz.com/edit/vitejs-vite-fgrdqd?file=src/App.tsx

**Problem description**:

https://user-images.githubusercontent.com/46083126/199187995-9d552760-71c1-4eca-b9ea-d8800c75234b.mp4

**Suggested solution**:

N / A

**Comment by silviuaavram** [comment]
It's a hard cookie. The issue is that, on click, you open the menu with `openMenu` because of mouse focus, then ToggleButtonClick state event happens, sees that menu is open, so it closes it.

I cannot think of something intelligent to handle it at the moment.

You can try some dark magic though. In a boolean ref, in onFocus, turn it to true. In a stateReducer, on toggle button click, check if you opened the menu with openMenu (via the ref value), and if you did, keep isOpen as true, make the ref false either way.

Something like that should work, but if find something better, let us know!

https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#statereducer
