### ISSUE TITLE
How does one avoid losing focus on input when using tab auto-complete?

### ISSUE THREAD

**Issue by qwbarch** [downshift-js/downshift#1446]
- `downshift` version: 7.0.4
- `node` version: 16.17.1
- `yarn` version: 1.22.18

**Problem description**:
When using the ``tab`` key to select a menu item, the input focus is lost.

**What I expect**:
Pressing tab should auto-complete the item (which it does), and then allow me to continue typing.

**What happened**:
The input loses focus and it shifts over to my browser's menu bar instead.

**Reproduction repository**:
https://github.com/qwbarch/downshift-reproducible/blob/main/src/App.tsx

**What I've tried**:
I assumed I could fix this by preventing the default behaviour of ``tab``.
```typescript
function onKeyDown(event: React.KeyboardEvent<HTMLInputElement>) {
    if (event.key === "Tab") {
      event.preventDefault();
      event.currentTarget.focus();
    }
  }
```
https://github.com/qwbarch/downshift-reproducible/blob/58aeacb131dec2f0caf68c0fa4df5dc173e40480/src/App.tsx#L38

Unfortunately, this seems to prevent the event from propagating down to downshift's event listener, making the tab autocomplete not work altogether.  

How can I prevent the ``input`` from losing focus when using tab auto-complete?

**Comment by btslater** [comment]
I wonder if you could `focus()` the input element itself using a `ref` instead of using `event.currentTarget`?

I would also love an answer to this question as it seems like a realistic expectation for users that Tab would select highlighted items, especially if they have familiarity with code editors that allow Tab for autocompletion (like VS Code).

**Comment by silviuaavram** [comment]
Hi! I don't think the expected behaviour you are describing is correct. If you use Tab to select, focus should move to the next actionable element in the tab order. If you want to keep focus after selection, use Enter or Click.

https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-list.html

**Comment by qwbarch** [comment]
Thanks for the reply! Is there a way for me to make this functionality work regardless?
Discord's emote auto-complete works like this and I'd like to make it as close to it as possible

**Comment by silviuaavram** [comment]
```tsx
          {...getInputProps({
            onKeyDown(event) {
              if (event.key === 'Tab') {
                event.preventDefault()
                highlightedIndex > -1 && selectItem(items[highlightedIndex])
              }
            },
          })}
```

Maybe this? Make sure you test it so it does not break any other use case.

**Comment by qwbarch** [comment]
Oh that works, thanks a lot!
