### ISSUE TITLE
Calling `getItemProps` without `index` breaks default `onClick` event handler

### ISSUE THREAD

**Issue by DavidPhilip** [downshift-js/downshift#1469]
- `downshift` version: 7.2.0
- `node` version: 16.17.0
- `npm` (or `yarn`) version: 1.22.19

**What you did**:
I've used `getItemProps` like this since the list the combobox manages doesn't match what the UI displays, f.e. if you do some grouping / sorting when rendering the list, so I can't use the index at that time:

```javascript
getItemProps({ item })
```

According to https://www.downshift-js.com/use-combobox `getItemProps` can be called with `item` only. There's no mention of it limiting its functionality.

**What happened**:
When omitting the `index` prop of the `getItemProps` call the `onClick` handler doesn't work.

**Problem description**:
After having a closer look it seems it seems the dispatched `index` will always resolve to the passed `index` which in this case is `undefined`:

```javascript
const itemHandleClick = () => {
  dispatch({
    type: stateChangeTypes.ItemClick,
    index, // this is always `undefined`
  })
}
```

**Suggested solution**:
Could we use `itemIndex` instead of `index`?

```javascript
const itemIndex = getItemIndex(index, item, latestProps.items)

...

const itemHandleClick = () => {
  dispatch({
    type: stateChangeTypes.ItemClick,
    index: itemIndex,
  })
}
```

**Comment by silviuaavram** [comment]
Thank you for reporting this! I did not have time to look more deeply into it, but it does seem that you have a point and it's a bug.

I am in the process of changing this code a bit as a consequence of adding isItemDisabled prop instead of accepting disabled as getItemProps, and I performed the following changes. Maybe you can use these changes and open a PR to fix it right a way?

```js
// hooks/useCombobox/index.js

  const getItemProps = useCallback(
    ({
      item: itemProp,
      index: indexProp,
      onMouseMove,
      onClick,
      refKey = 'ref',
      ref,
      ...rest
    } = {}) => {
      const {state: latestState, props: latestProps} = latest.current
      const [item, index] = getItemAndIndex(
        indexProp,
        itemProp,
        latestProps.items,
      )
// ... and use index and item throughout the function.
```

```
// hooks/utils.js

function getItemAndIndex(indexProp, itemProp, items) {
  let item, index

  if (itemProp === undefined) {
    if (indexProp === undefined) {
      throw new Error('Pass either item or item index in getItemProps!')
    } 

    item = items[indexProp]
    index = indexProp
  } else {
    index = items.indexOf(itemProp)
    item = itemProp
  }

  return [item, index]
}
```

Looking forward to the PR! It should cover both useSelect and useCombobox.

Also you can add some unit tests to the getItemProps that catch this issue. Since this bug slipped through our code, our tests require an update.

Thank you!
