### ISSUE TITLE
Only the last toggle element is able to close the menu

### ISSUE THREAD

**Issue by richard-lopes-ifood** [downshift-js/downshift#1493]
- `downshift` version: ^7.1.0
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

**Relevant code or config**

```javascript
<div style={toggleElementStyles} {...getToggleButtonProps()}>
  {selectedItem ?? 'Elements (toggle 1)'}
</div>

<div style={toggleElementStyles} {...getToggleButtonProps()}>
  {selectedItem ?? 'Elements (toggle 2)'}
</div>
```

**What you did**:
Use `getToggleButtonProps` more than once.

**What happened**:

Only the last toggle element is able to close the menu.

**Reproduction repository**:

https://codesandbox.io/s/pensive-framework-f9b66m?file=/src/hooks/useSelect/basic-usage.js

**Problem description**:

Only the last toggle element has the ability to close the menu.

**Suggested solution**:

Let all elements that invoke getToggleButtonProps to be able to close the menu, not only the last one.

**Comment by silviuaavram** [comment]
Hi! Thanks for using downshift!

getToggleButtonProps is not just for menu toggle, it's adding more than that to your toggle element. Also, it needs to identify the toggle element for the logic that happens inside useSelect.

Since your usage is different from a standard select (toggle element, label, menu and items), you can grab `toggleMenu` from useSelect and use that on a second element onClick. Just keep in mind that the second element will only do the toggling, it will not have the rest of the event handlers and HTML attributes from getToggleButtonProps.

And it should not. Having 2 toggle elements with the same attributes confuses users, since there is no such thing as a select with multiple toggles. You should be aiming for consistency of patterns and accessibility. If a user will come across your first toggle, they will know what to do, because useSelect provides the element with all the functionality. But once they will come across your first toggle, with the same attributes, opening the same menu, they might ask themselves what was the first toggle for anyway.
