### ISSUE TITLE
Question about role="combobox" in useSelect

### ISSUE THREAD

**Issue by seanhuggins1** [downshift-js/downshift#1494]
https://github.com/downshift-js/downshift/blob/7200d446d630fd72a2b40b858d8809f8355f5421/src/hooks/useSelect/index.js#L403

Hi there! Love the work on this library. I've just integrated it into our application & things are working great.

I just had a question about `role="combobox"` being on the `useSelect` toggle button? I am guessing this is right, & just a weird quirk with ARIA that a select component has this `combobox` role, but I just wanted to double check.

Thanks!

**Comment by silviuaavram** [comment]
Hi, thank you for using downshift!

Regarding your question, we apply the attributes the way ARIA recommends it, via its version  1.2 spec. You can check it out [here](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/).

As for the reason they added combobox as role to a select, I'm not sure. Maybe they want to align the combobox and select concepts a bit more, since a select can be considered a selection only combobox. Yes, you cannot type search queries in it, but you can still search via character keys.

For other differences between the 1.2 pattern and the native html select, I believe ARIA is looking for convenience, and wants to spec accordingly. In any case, the aria spec should be the common point for every stakeholder of selects/comboboxes: user, screen reader developer, front end developer etc.

**Comment by seanhuggins1** [comment]
Interesting! The alignment idea makes sense. Thanks for clearing that up :)
