### ISSUE TITLE
Cannot disable onblur of togglebutton in useSelect

### ISSUE THREAD

**Issue by Wme76** [downshift-js/downshift#1503]
- `downshift` version: 7.6.0
- `node` version:14.17.0
- `npm` (or `yarn`) version:6.14.13

**Relevant code or config**

Part of the code but reproducible in codesandbox of multiple useselect example
https://codesandbox.io/s/nifty-meninsky-o5m9gf?file=/src/hooks/useMultipleSelection/select.js

```javascript
// customise getToggleButtonProps 
{...getToggleButtonProps({
  onBlur: (e:FocusEvent) =>{
    e.nativeEvent.preventDownshiftDefault=true
  }
})}
```

**What you did**:
I couldnt disable togglebuttonblur from taking place in state reducer. My ideal would be to preventdownshiftdefault in togglebutton onblur but couldnt get it to work.

Customising onBlur in getToggleButtonProps to preventdownshiftdefault didnt work. Neither did overriding onBlur

**What happened**:
onBlur event fires with preventdownshiftdefault set to true but toggleButtonBlur state change still triggers and menu closes

**Reproduction repository**: none

**Problem description**:

**Suggested solution**:

**Comment by silviuaavram** [comment]
```js
        {...getToggleButtonProps({
          onBlur(e) {
            e.preventDownshiftDefault = true
          },
        })}
```

However, why do you need this behaviour?

**Comment by Wme76** [comment]
Hi @silviuaavram many thanks for looking into this. My problem i cannot get e.nativeEvent.preventDownshiftDefault in onBlur to not trigger the statereducer

my use case is i have additional UI like headers in the menu that will trigger toggleButtonBlur when clicked on and cause menu to close which i don't want

**Comment by silviuaavram** [comment]
useMouseAndTouchTracker is internal logic for clicking and touching in the toggle + menu area, and is complex enough.

Maybe just go with fully controlling `isOpen` and perform your own logic on when to open and close the menu. onStateChange with ToggleButtonBlur should tell you when blur occurred, then you can check where the focus is and keep the menu open / close it according to that information.

Having actionable elements inside a Select menu is not ideal, since the widget is all about picking an option from a list that's collapsible and searchable, but if you really need those actionable elements in the items, you need to handle this use case your own. Just make sure the resulting Select is still accessible with screen readers and keyboard.
