### ISSUE TITLE
onSelect is called with undefined when clicked on escape

### ISSUE THREAD

**Issue by venkateshwarreddyr** [downshift-js/downshift#1542]
- `downshift` version: 8.1.0
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did**:

**What happened**:

**Reproduction repository**:

**Problem description**:
onSelect is called with undefined when clicked on escape with empty values

Reproduction Steps 
1. Sandbox:
https://codesandbox.io/s/downshift-how-to-reset-inputvalue-after-running-onselect-forked-fqmqch
2. click on input field
3. click on escape
3. (issue) onSelect is called (this should not happen)

<img width="1107" alt="image" src="https://github.com/downshift-js/downshift/assets/51945078/66ff3f52-839f-4d6a-beed-91d97a51d930">

Expected:
When clicked on Escape button it should not call onSelect function.

**Suggested solution**:

**Comment by venkateshwarreddyr** [comment]
@silviuaavram can you pls check this?

**Comment by silviuaavram** [comment]
This check has been around for quite some time `isItemSelected = newStateToSet.hasOwnProperty('selectedItem')` and I don't think I'm going to do any more changes in Downshift, since we are using `useCombobox` now.

So, add a check for undefined in your handler, if you don't want to do anything in that case. I don't think the behaviour is totally wrong, since the `selectedItem` does change on Escape. If there was a `selectedItem` before and you hit Escape, now it should be `undefined`, and onSelect helps you know that.

I would also switch from Downshift to useCombobox, too. Thanks!
