### ISSUE TITLE
Escape should clear text in input

### ISSUE THREAD

**Issue by silviuavram** [downshift-js/downshift#680]
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

Escape key inside input should clear the text from it. Currently we are resetting it to the string value of the item.

**Comment by babzcraig** [comment]
If no one is on this yet, I'd like to take this on @silviuavram. I've read the requirements on the w3 page and can make a PR for this

**Comment by silviuavram** [comment]
That is great to hear! It's all yours, let me know when I can help out. Thanks!

**Comment by silviuavram** [comment]
@babzcraig how is the progress on this one? need any help? :)

**Comment by gaskar** [comment]
hi @silviuavram I can take this one.

**Comment by babzcraig** [comment]
@gaskar please feel free to. I couldn't get downshift's `validate-setup` command to work and I've been too swamped to debug for a while. @silviuavram perhaps you can help me with this and I can take on another issue. Thanks!

**Comment by gaskar** [comment]
@babzcraig seems there is a problem with cypress tests, I've tried different versions nothing is working beside of just commenting out these tests, seems that @silviuavram created PR for this problem but it is failing as well
https://github.com/downshift-js/downshift/pull/661

**Comment by babzcraig** [comment]
I see. I had just changed my development machine so I though maybe I hadn't set up things well yet. I might have to do the same then. If you want to take this issue, please do. I won't be available until Sunday so I'll just pick another issue then if you're on this

**Comment by brandonkal** [comment]
This should be reconsidered. Escape is usually used to blur an element. Clearing the textbox is an unexpected side effect.

See: https://github.com/w3c/aria-practices/issues/1066
Reverting this is already planned for aria-practices 1.2

Just to provide some additional examples, try pressing escape in the "Search or jump to..." box above or any search engine.

The only other place I have seen this pattern is in the Mac System Preferences search box, but this is done in tandem with removing focus on the input, which is the expected behavior.

**Comment by filipjnc** [comment]
Please reopen the issue, as there is a new official guideline by ARIA:
The Escape key should only clear the input, if the dropdown is **not** currently open.
Source: https://github.com/w3c/aria-practices/pull/1129
