### ISSUE TITLE
hooks api

### ISSUE THREAD

**Issue by sibelius** [downshift-js/downshift#683]
Every render props can be replaced with hooks api

I think it makes sense to provide hooks apis for downshift, after the hooks apis landed, we can start rewriting the core of it to use hooks

what do you think?

related to this https://twitter.com/sseraphini/status/1102602849152843776

**Comment by silviuavram** [comment]
it makes sense and I like the idea. I just did not have time myself to explore it.

**Comment by sibelius** [comment]
this could be a good benchmark https://github.com/react-dropzone/react-dropzone

**Comment by hardiked** [comment]
I have just started looking at hooks and it is really amazing. I like the idea to rewrite it with hooks.

**Comment by steveoh** [comment]
This package can still be used in a function component using hooks without any changes correct?

**Comment by elsangedy** [comment]
Hey guys, what do you think? any suggestion? I'll work in a PR

https://github.com/elsangedy/use-downshift

**Comment by silviuavram** [comment]
That is great news! I only wished that this did not appear out of nowhere. But nevertheless it's very awesome work and we should aim to collaborate for a unified better solution.

I am also working on https://github.com/silviuavram/downshift-hooks. I am close to release it as npm which is what I will do since I came this far. My idea was to start with a normal dropdown hook and have hooks for each: dropdown and combobox, single and multiple. Those are different patterns in ARIA and maybe it's better to have separate logic for each.

What do you think?

**Comment by sibelius** [comment]
can we run both implementation on tests of this repo, so we can make sure they don't break anything

**Comment by elsangedy** [comment]
@silviuavram great job with `downshift-hooks`!
I agree with you and I think we should follow through with your project, I would like to help.

@sibelius good idea, we can try to apply the same test suite of this repo

**Comment by silviuavram** [comment]
https://github.com/downshift-js/downshift/pull/860 code already in for `useCombobox` Will release tomorrow.
