### ISSUE TITLE
Preact 10 support

### ISSUE THREAD

**Issue by gevalo1** [downshift-js/downshift#700]
- `downshift` version: v3.2.7
- `node` version: v10.11.0
- `npm` (or `yarn`) version: npm 6.4.1

**Problem description**:

Downshift does not work with Preact 10 (currently still alpha, 10.0.0-alpha.4 at the time that I create this issue), are there already any plans to support the new Preact version?

**Comment by silviuavram** [comment]
I did not work with Preact so far so I don't know. What does not work? Can you help fixing the problem?

**Comment by apfelbox** [comment]
Hi, 

the beta doesn't seem to work as well:

https://codesandbox.io/embed/simple-downshift-example-eccbd

It just fails with:
![2019-06-14 at 17 39](https://user-images.githubusercontent.com/1032411/59520926-5bbb0800-8ecb-11e9-9e7e-a467772695f9.png)

even if we just returns simple DOM elements:

![2019-06-14 at 17 39](https://user-images.githubusercontent.com/1032411/59520948-670e3380-8ecb-11e9-9bd5-6256e4da98bf.png)

You can even reduce it to this reproducible case:

```jsx
<Downshift>
    {() => <div />}
  </Downshift>,
```

**Comment by apfelbox** [comment]
@silviuavram does my example help you in pinpointing the issue?

**Comment by silviuavram** [comment]
@apfelbox I don't have the bandwidth to work on this issue on the moment, my focus is in rewriting the library with hooks so I am fully committed on experimenting in that area.

If you can fix the problem I can help you with a review. Thank you for the effort!

**Comment by francoischalifour** [comment]
I tried tweaking Downshift on my side to make it compatible with Preact X. It turns out is already mostly is, but the hacks to make it compatible with Preact 8 now don't work because Preact X internals ressemble more React.

Here are the 3 only elements I noticed that need to be updated.

### `isDOMElement` must check `element.type`

Preact 8's `nodeName` VNode property is now called `type`, like in React. This is relied upon in `isDomElement`. This check is misleading Downshift and needs to be extended.

This change should do the trick:

```diff
function isDOMElement(element) {
-  if (isPreact) {
-    return typeof element.nodeName === 'string'
-  }

-  return typeof element.type === 'string'
+  return typeof element.type === 'string' || typeof element.nodeName === 'string'
}
```

- [See Preact source](https://github.com/preactjs/preact/blob/40a92458ce2bbf2dfc0ceec9864c8e7cf8d058e4/src/index.d.ts#L14)
- [See Downshift source](https://github.com/downshift-js/downshift/blob/8f987928e6a0ff4d0d9e6259748bcd243532f0ec/src/utils.js#L190)

### `getElementProps` must check `element.props`

Preact 8's `attributes` VNode property is now called `props`, like in React. This is relied upon in `getElementProps`. This check is also misleading Downshift and needs to be extended.

```diff
function getElementProps(element) {
-  if (isPreact) {
-    return element.attributes
-  }

-  return element.props 
+  return element.props || element.attributes
}
```

- [See Preact source](https://github.com/preactjs/preact/blob/40a92458ce2bbf2dfc0ceec9864c8e7cf8d058e4/src/index.d.ts#L15)
- [See Downshift source](https://github.com/downshift-js/downshift/blob/8f987928e6a0ff4d0d9e6259748bcd243532f0ec/src/utils.js#L206)

### Preact X `cloneElement` is not part of the default export

Preact X doesn't seem to export any defaults. `cloneElement` is a named export so `React.cloneElement` fails on that line:

https://github.com/downshift-js/downshift/blob/07366a8ecfd02a5418be6c23f270a5e77e0ac7b2/src/downshift.js#L1196-L1199

Changing the import to the following works because we don't use other React members in this file:

```diff
- import React, {Component} from 'react'
+ import {Component, cloneElement} from 'react'
```

And then use:

```diff
- return React.cloneElement(element, this.getRootProps(getElementProps(element)));
+ return cloneElement(element, this.getRootProps(getElementProps(element)));
```

---

Let me know if this seems right to you and I can send a PR! Looking forward to using Downshift with Preact X.

**Comment by francoischalifour** [comment]
// @silviuavram @kentcdodds 

In case this was left unnoticed, https://github.com/downshift-js/downshift/issues/700#issuecomment-511231148 should add support for Preact X. Let me know if this is part of your roadmap so that I send a PR.
