### ISSUE TITLE
Skip selecting disabled items

### ISSUE THREAD

**Issue by letterix** [downshift-js/downshift#728]
- `downshift` version: 3.2.10
- `node` version: 11.13.0
- `npm` (or `yarn`) version: 1.15.2 (yarn)

**Relevant code or config**

```javascript
  const ariaProps = disabled
    ? {}
    : getItemProps({
        key: d.id,
        item: d,
        isSelected: highlightedIndex === index,
        index,
      });
```

```javascript
  const ariaProps = getItemProps({
    key: d.id,
    item: d,
    isSelected: highlightedIndex === index,
    index,
    disabled,
  });
```

**What you did**:
Trying to create a custom date input where some of the dates are disabled. The dates in the calendar should be accessible via the arrow keys.

**What happened**:
Tried both of the above code snippets, but can't get the highlightedIndex to work properly. No matter how I disable the items, their index is still present as 'highlightedIndex'.

**Problem description**:
I want to be able to skip selecting the disabled items when using the keyboard for navigation.
I might be misunderstanding something, so please excuse my ignorance.

Isn't the disabled property of getItemProps supposed to remove the item from the logic of navigation and such?

**Comment by silviuavram** [comment]
I see. Your second example is ok, if you pass `disabled` to `getItemProps` then that item will not be hovered and not selected. It can be highlighted using arrow navigation though. Not sure if we should jump it if the item is disabled.

Do you have any example of such widget? For reference.

**Comment by letterix** [comment]
Well, in my case that would be a calendar widget (drop down). The dates before the current date should be disabled (booking site). In our case, we want to navigate to the first available date, skipping the disabled ones.

What would be the purpose of selecting disabled items? Just out of curiosity :)

**Comment by silviuavram** [comment]
I see the point. You cannot select them, you cannot hover them. But the issue remaining is calculating the highlightedIndex when there are disabled items in the list.

Do you think you can implement this and create a PR?

**Comment by reverie** [comment]
Docs for the current solution:

https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V8.md#isitemdisabled

**Comment by akos-molnar** [comment]
Hello there!

I would like to re-visit this feature. I believe this behaviour now violates accessibility. Users who are fully abled are now gaining some advantage by knowing that certain elements are possible to choose just momentarily disabled. A blind person navigating with keyboard would skip these elements, they would never be notified about an existing but temporarily disabled option.

In such scenarios the option highlight should still be possible + allow screen readers to read the option. It should state the disabled status and possibly the reason by providing an `aria-description / -describedby`.

Also, as a fully abled user i would never expect to jump over a selection just because it is disabled, it is bad UX.

In such scenarios, like the OG asked, i believe a dummy placeholder element should have been added on their own code.

Would it be possible to somehow re-add the old functionality, for instance if the item has `aria-disabled` set as true within the `getItemProps`, it would still be highlighted, but not allowed for selection? Therefore a breaking change could be avoided if necessary.
