### ISSUE TITLE
Using Typescript with Preact?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [downshift-js/downshift#733]
It looks like the type definitions here explicitly refer to React. What does this mean for Preact users?

**Comment by silviuavram** [comment]
I can't help you on this one right now, I need to get acquainted with this part as well in the future though. I will leave this open, maybe someone else will pick it up.

**Comment by silviuavram** [comment]
is this one helping https://github.com/downshift-js/downshift/pull/802 ?

**Comment by vpzomtrrfrt** [comment]
No, the typings are still referencing React

**Comment by silvenon** [comment]
Even though this is more than a year old, I'll still answer for posterity: Preact has a compat module precisely so that React libraries like Downshift don't have to think about Preact compatibility. In `tsconfig.json` you have to map `react` to `preact/compat` like this:

```json
{
  "compilerOptions": {
    "paths": {
      "react": ["node_modules/preact/compat"]
    },
  }
}
```

or via a bundler like webpack, depending on your setup.

However, `preact/compat` is currently missing some type exports like `ReactNode`, so type check to fail, but this is not anything that Downshift should be concerned about.
