### ISSUE TITLE
Clearing out text field does not clear out state

### ISSUE THREAD

**Issue by zach446** [downshift-js/downshift#758]
I have implemented a search field with an infinite scroll list.  Upon finding the selection, using the stateReducer, I grab the clicked Item and assign it to the input value.  StateReducer can be seen below.

```javascript
function stateReducer(state, changes) {
  switch (changes.type) {
    case Downshift.stateChangeTypes.mouseUp:
      return {
        ...changes,
        inputValue: state.inputValue,
      };

    case Downshift.stateChangeTypes.clickItem:
      return {
        ...changes,
        inputValue: changes.selectedItem.attributes.NAME,
      };
    default:
      return changes;
  }
}
```

**The issue**

IF the user selects the item in the drop down, triggering the state change to show the selected value within the text box.  Then if the user were to select the text, currently within said text box, and hit delete it would not trigger any of the current state triggers and the inputValue would not change.

The solution I would propose is to create an `onKeyCode` type that allows the developer to assign a key code to look trigger on.  If not that then maybe just a way to tell when the input box has been emptied?

Here is a gist of my component that is utilizing downshift
https://gist.github.com/zach446/f1db64e0a2fc0b5433912bc1864a5695

Thanks!

**Comment by silviuavram** [comment]
First of all, you will achieve your
```
    case Downshift.stateChangeTypes.clickItem:
      return {
        ...changes,
        inputValue: changes.selectedItem.attributes.NAME,
      };
```
with passing `itemToString = item => item.attributes.NAME`

Secondly, you are probably right in this case. I am looking here: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html 

You select an item. Delete a part of its text. Blur. The text goes back to the way it was. But if you delete the whole text via backspace/delete then the text will not go back to the way it was on blur.

Our behavior matches the first part even if you delete the whole text. If you want to REALLY delete it (clear the selectedItem), use Escape.

We can probably fix this if you think it's blocking. I can help you with review if you create a PR. Otherwise my focus would be to implement the combobox design pattern better using a react hook. So creating a new one. Rather than patching this up. But if you want to fix it, I would be very happy. Good luck!

**Comment by zach446** [comment]
I will take a look at it over the next few days and see what I can come up with.  Cheers!
