### ISSUE TITLE
Can't control selectedItem from parent component using controlled props

### ISSUE THREAD

**Issue by mglace** [downshift-js/downshift#772]
I wrote a reusable autocomplete component using Downshift.  The component encapsulates a lot of Relay logic for fetching data from my GraphQL endpoint.  I have a use case where the parent component needs to receive the selectedItem, display the name property of the selectedItem, then clear out the selectedItem of the autocomplete (think selecting and displaying multiple tags).  Problem is I can't seem to control the selectedItem of the autocomplete from the parent component.  I'm sending down the selectedItem as null to the autocomplete yet the selectedItem remains the chosen item. 

- `downshift` version: 3.3.1
- `node` version: 10.15.3
- `yarn` version: 1.17.3

**Relevant code or config**

Sample code with Relay stripped out for simplicity:
https://codesandbox.io/embed/spring-fire-um1xh

**Steps to reproduce**

- Type the word "Item" into the textbox
- Click on one of the three results that are displayed

**Outcome**

- Title of parent component and inputValue/selectedItem of autocomplete are both set to value of item chosen

**Desired Outcome**

- Title of parent component set to value of item chosen
- inputValue/selectedItem of autocomplete cleared out

**Comment by silviuavram** [comment]
https://codesandbox.io/s/epic-wildflower-vncxg

Hello. You are correctly controlling `selectedItem`, it is null, but you also have to control `inputValue` since in this case it will not be updated. It will be updated with `itemToString(selectedItem)` but with the `selectedItem` from Downshift, not from your controlled prop.

You can either control `inputValue` and make it empty in your `onChange` prop. And of course update it on normal typing using `onInputValueChange`.

Or you can capture selection actions with `stateReducer`, return null for `selectedItem` and empty string for `inputValue`. https://github.com/downshift-js/downshift#statereducer

Good luck and let me know if you fixed it.

P.S. added some changes / improvements in based on your sandbox, gave you a link above.

**Comment by mglace** [comment]
@silviuavram - Thanks for your reply.  I think I'm starting to understand.  Just a few points for clarity.

> You are correctly controlling selectedItem, it is null, but you also have to control inputValue since in this case it will not be updated. It will be updated with itemToString(selectedItem) but with the selectedItem from Downshift, not from your controlled prop.

I was under the impression that if you pass a selectedItem prop into Downshift that it would pass your selectedItem prop into itemToString instead of it's internally managed selectedItem.  From what you describe above, this is not the case?

I understand now that I also need to manage the inputValue prop in addition to the selectedItem prop to accomplish what I need.  I was trying to avoid that as the parent component manages five Downshift components and managing their inputValue and selectedItem will make for some rather complicated and unruly code.  

I'm actually considering forking my Autocomplete component out to another component (AutoClearingAutocomplete) for this particular use case so I can encapsulate and reuse this functionality.

> P.S. added some changes / improvements in based on your sandbox, gave you a link above.

One of the improvements you made to my code was to initialize the items in the Autocomplete component so that the menu opens when you start typing in the input control.  I intentionally did not initialize the items array because I was trying to simulate the GraphQL call to get the results.  With this in mind, is it ok to initialize items to an empty array or do you recommend another method?

Thanks!

**Comment by silviuavram** [comment]
I did that init because I felt I need to do one step more in order to get the list of suggestions. But maybe I was wrong.

I don't know what to suggest, anything that fits your case really. Just make sure that when user types one character the list of suggestions has options for that character.

Good luck!
