### ISSUE TITLE
Show multiple lines within input upon item selection

### ISSUE THREAD

**Issue by haleybarlar** [downshift-js/downshift#815]
- `downshift` version: 3.2.7
- `node` version: 12.6.0
- `npm` (or `yarn`) version: 6.9.0

![IMG_7303](https://user-images.githubusercontent.com/40280230/67968501-ce711980-fc07-11e9-8c0f-78d7a5e0b5c0.jpg)

**Problem description**:
When an item is selected, the input currently is only able to show one line (from what I can gather).

**Suggested solution**:
I would like to see the input show multiple lines upon selection of an item. In my case, I am using Downshift as an address search and I'd like to be able to show the address's name and description on separate lines.

**Comment by milosmns** [comment]
Woah this is the best ticket description ever! 🥇

**Comment by hwclass** [comment]
I think that's one of the missing thing that would be great to have in downshift! 👏 This can be an extra configuration parameter can be passed & modifiable 💯

**Comment by silviuavram** [comment]
1. Downshift does not control what you render, that's up to you.
2. That is not an `<input>` anymore, it's a `<textarea>`.

If you want to achieve your design, use a textarea instead of the input (not really the combobox pattern) and use `itemToString` to render the string equivalent of your item however you want.

But you may want to revisit what it is that you want, check other similar solutions etc.

**Comment by haleybarlar** [comment]
Hi @silviuavram thanks so much for your response! I replaced my input with a textarea, and it works great 👍🎉
