### ISSUE TITLE
Issue with fast-memoize

### ISSUE THREAD

**Issue by apuntovanini** [downshift-js/downshift#845]
With latest version 3.4.5 using fast-memoize doens't allow passing items with other than string attributes. I I pass a list of items like this:

```javascript
items={[
  {
    id: 'target',
    name: <FormattedMessage defaultMessage="Target campaign" />,
    description: (
      <FormattedMessage defaultMessage="Target campaigns have a funding target and a duration, use this for special projects" />
    ),
    before: (
      <FormattedMessage defaultMessage="Target campaign">
        {alt => (
          <img
            src={require('../../../assets/target-donation-campaign.svg')}
            css={{ width: 96 }}
            alt={alt}
          />
        )}
      </FormattedMessage>
    ),
  },
  {
    id: 'classic',
    name: <FormattedMessage defaultMessage="Classic campaign" />,
    description: (
      <FormattedMessage defaultMessage="Classic campaigns are always open, show up in your profile as donation destinations options" />
    ),
    before: (
      <FormattedMessage defaultMessage="">
        {alt => (
          <img
            src={require('../../../assets/classic-donation-campaign.svg')}
            css={{ width: 96 }}
            alt={alt}
          />
        )}
      </FormattedMessage>
    ),
  },
]}
```

JSON stringify fails. It used to work without problems, and passing components to items allowed for great flexibility in how the select was rendered.
If items should have a specific format, I guess it's useful to include it in the docs.
What are your thoughts? Is there any ways to use getItemProps without memoize?
Thanks!

**Comment by silviuavram** [comment]
We should fix this soon. maybe the `item` should not be included as the memoize parameter, but a way to uniquely identify the item. Like the id of the item for instance.

`getItemId` would not be useful in this case since that will just create IDs in the DOM at would not work to uniquely identify items. Maybe another getter prop similar to `itemToString` ? What do you think?

Basically we should not return those attributes and handlers if the item X is still on position Y. Y is the `index`, X can be this value from the new getter prop.

Do you think of any better way?

**Comment by apuntovanini** [comment]
I think the solution you described (prop getter similar to `itemToString`) is a very good one indeed. Something like `itemKey` or `itemToKey`? Dunno :)
Can I help somehow?

**Comment by silviuavram** [comment]
I am thinking to revert the previous PR as a fix for this case, then add it as a feature release, since we are going to add a prop.
