### ISSUE TITLE
Is `prop-types` really necessary?

### ISSUE THREAD

**Issue by pedroapfilho** [downshift-js/downshift#870]
Hi, all!

What if we change the text:

```
This package also depends on react and prop-types. Please make sure you have those installed as well.
```

to

```
This package also depends on react. Please make sure you have it installed as well.

If you're using Typescript or Flow you don't have to do anything, if you're using Javascript you need to install prop-types.
```

**Comment by TLadd** [comment]
It looks like that wording was around when prop-types was listed as a peerDependency, at which point it made sense.

Since prop-types is now correctly a dependency instead, I don't think there should need to be any mention of prop-types in the README at all. Since it's in dependencies, it will be brought in and work as expected regardless of whether a consuming project uses prop-types itself.

**Comment by pedroapfilho** [comment]
I'll write a PR for that
