### ISSUE TITLE
Filtering inside the menu

### ISSUE THREAD

**Issue by matyushen** [downshift-js/downshift#888]
- `downshift` version: 4.0.2
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**
See the links below.

**What you did**:
I'm working on a dropdown select component that has an input field inside the dropdown for filtering.
My current solution is something like a custom button that opens a portal with `useCombobox` that has the menu always open. Kind hacky and not fully accessible. Also, suffers from #884.

**What happened**:
I spent some time to figure out how I can use `useSelect` or `useCombobox` to achieve implement the feature, but wasn't able to get it working. 

Other options I tried:
- Normally use `useSelect` and place custom filtering input inside. But it seems not possible to make it work, because the menu gets closed the moment you click on the input. https://codesandbox.io/s/useselect-usage-n3vtj. Latest attempts here: https://codesandbox.io/s/useselect-usage-whcdn
- Use `useCombobox` but move the input inside the menu. In that case, filtering doesn't work and a11y is broken https://codesandbox.io/s/usecombobox-usage-y1dfd

**Reproduction repository**:
See the links above.

**Problem description**: Not really a problem I guess, rather a feature request. Because existing hooks do not provide that flexibility.

**Suggested solution**: Anyone else tried to do something similar? Is it a common patter at all? I'd appreciate any suggestions.

**Comment by silviuavram** [comment]
Why not change the design altogether and go for a normal combobox with toggle button? And the use normal useCombobox. I don't see much point in having the filter inside the menu to be honest, as it will impact focus management, since the input should be focusable. It's a pain.

And if you use `useSelect` then you don't need the filtering input that much, as when you have the menu opened, you can just hit character keys and they will highlight items starting with those keys.

I would aim for a standardised widget in any way, either combobox or select. The one you are suggesting will be a very big pain to handle the focus. 

https://github.com/downshift-js/downshift/issues/884 has been fixed btw.

**Comment by AfrazHussain** [comment]
@matyushen Did you ever manage to get around this? I've got a similar functionality of filtering a list inside a dropdown, but I've come to the exact same standstill that you are/were at. Would appreciate some help here. :)

**Comment by nirbenya** [comment]
I also need this functionality but currently fighting with our design team and trying to explain to them that this is not accessible or a common behavior

**Comment by joonass-visma** [comment]
@matyushen Probably comes too late but filtering in your `useCombobox` sandbox doesn't work because you render `items` instead of `inputItems`. Not sure what the accessibility problem is but I've seen this pattern elsewhere, f.e. Semantic UI Dropdown component supports it.
