### ISSUE TITLE
[useCombobox] Expose input focus change type when input field receives focus

### ISSUE THREAD

**Issue by weyert** [downshift-js/downshift#894]
- `downshift` version: 4.0.4
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Problem description**:
I would like to open the listbox straight away when the input field receive focus only currently this is not possible because of `InputFocus` isn't exposed while `InputBlur` is.

**Suggested solution**:
I would suggest that we introduce this `InputFocus`-type for the reducer too.

**Comment by silviuavram** [comment]
I will keep this open for now to get feedback.

Opening on focus is not something standard or required by aria patterns. I may be wrong, but I did not see it.

`InputFocus` is not something I will add to reducer for now since it will not trigger any state change. `InputBlur` does trigger state change, that is why we have it added.

You can probably achieve this by `openMenu` as a `onFocus` callback supplied to `getInputProps`. https://codesandbox.io/s/usecombobox-openmenu-on-focus-zinf1

**Comment by weyert** [comment]
Thank you, I will have a look at the sandbox :)

**Comment by jorgemoya** [comment]
Why not just add `onFocus: openMenu` to your `input`?

**Comment by weyert** [comment]
Yeah, sorry, I was over complicating things! Closing this ticket

**Comment by JClackett** [comment]
Adding the "onFocus: openMenu" stops the onClick on item working for me, it now won't add it to the selectedItems?

**Comment by silviuaavram** [comment]
Can you describe the bug @JClackett and also share a codesandbox?

**Comment by JClackett** [comment]
https://codesandbox.io/s/recursing-water-8fl00?file=/src/hooks/useMultipleSelection/combobox.js

So I've added the onFocus={openMenu} to the input, just adding that stops the onClick on item from working, I assume its something to do with the stateReducers or onStateChange that im unaware of?

**Comment by silviuaavram** [comment]
try
```javascript
                  if (!isOpen) {
                    openMenu()
                  }
```

**Comment by silviuaavram** [comment]
This happens because when you click an item, the input gets blurred. Then as a side effect, we focus the input from useCombobox, and combined with a simple openMenu it may trigger a chain of events that prevent selection.

Maybe there is a bug in our code that we should fix. If you want to take a look at it and fix it would be great!

**Comment by JClackett** [comment]
adding that if block seems to solve it for now :) I don't have the time to go through the src at the moment, but I really appreciate the time you have given me to fix this! 🙌
