### ISSUE TITLE
[Suggestion/Hooks] Add option to remove scroll when combobox menu is open

### ISSUE THREAD

**Issue by ncesar** [downshift-js/downshift#951]
- `downshift` version: latest
- `node` version: latest
- `npm` (or `yarn`) version: latest

**Relevant code or config**

```
  const removeScrollOnOpen = isOpen => {
/* isOpen is coming from useCombobox */
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'auto';
    }
  };
  useEffect(() => {
    removeScrollOnOpen(isOpen);
  }, [isOpen]);

/* and in my combobox button */
     <S.ComboboxButton {...getToggleButtonProps({ onClick: removeScrollOnOpen })} aria-label="toggle menu" />
```
**Problem description**:  We still have scroll when the combobox menu is open.

**Suggested solution**:  My suggestion is to follow the normal select behavior(and also material ui) and remove the scroll if the menu is open. I did a simple code with hooks that do this behavior. The idea is that you can adapt this code and add a new prop like disableScrollOnOpen so its easier to use.

I searched through the issues/docs and found nothing about it. Sorry if I missed something.

**Comment by silviuavram** [comment]
Not sure if the problem is scroll as it's the focus applied to the menu when it's opened.

We are not messing with scroll and styles as users are free to do their UI in any way they see fit. However, that focus on the list is mandatory as it will make screen readers enter Forms Mode while they interact with the menu.
