### ISSUE TITLE
useCombobox: crash when all items are disabled and navigating up

### ISSUE THREAD

**Issue by dorianamouroux** [downshift-js/downshift#961]
- `downshift` version: latest
- `node` version: ?
- `npm` (or `yarn`) version: ?

**What you did**:

Open the combobox with the arrow. The use the keyboard arrow-up; the page crashes.

**What happened**:

![Screen Shot 2020-02-28 at 12 53 21](https://user-images.githubusercontent.com/13302836/75546664-5980e580-5a29-11ea-961e-12ba820dcda6.png)

**Reproduction repository**:

https://codesandbox.io/s/usecombobox-usage-kd0hu

**Problem description**:

The Combox doesn't give the proper `highlightedIndex` when using arrow-up over disabled items; the circular navigation doesn't matter.

**Suggested solution**:

Before returning a new `highlightedIndex`, make sure this index exists in the `items`.

**Comment by silviuavram** [comment]
Hi, is the sandbox link wrong? I cannot repro it.

**Comment by dorianamouroux** [comment]
I can still reproduce with that link, maybe I wasn't clear enough with the instruction.

Another way to reproduce is by clicking on the text input, writing the character `a` and pressing the arrow up

**Comment by silviuavram** [comment]
Are you sure about the link? I cannot see any `disabled` on the `getItemProps`.

**Comment by dorianamouroux** [comment]
I indeed didn't save the file, I thought it was automatic. Sorry about that!

**Comment by silviuavram** [comment]
Ok, better. The use case should not be that common so it's fine, no need to panic. But we should definitely fix it.

Luckily the logic that returns the index is in one place for every use. Can you take a look and fix this case? It seems that we are not returning the correct index if all items are disabled.

**Comment by levint** [comment]
I'm able to encounter the same "invalid target" issue and it seems like the cause is due to `highlightedIndex` being not up-to-date with the filtered items based on the current input value.

This happen to occur if the combobox filters the items based on input value (e.g. startsWith, fuzzy). Since new items are being returned, it could happen that the element's index`highlightedIndex` is trying to refer to has already changed.

`itemRefs` changed:
`scrollIntoView(itemRefs.current[highlightedIndex], menuRef.current);`
