### ISSUE TITLE
Is there any way to prevent select item on list item click?

### ISSUE THREAD

**Issue by IzaGz** [downshift-js/downshift#972]
"downshift": "^3.4.1",
node.js v11.15.0
 (npm v6.7.0)

I have` <ul> with <li>` s inside downshift, when i click on specific li item i need to perform some action, but not select the item. I dont need to disable the item. But i need to prevent it from selection, just do some actions that  need , when clicking it. 
Is there a way?

**Comment by silviuavram** [comment]
There are many ways. If you want only on click, you can try to use `preventDownshiftDefault`. Something like [here](https://github.com/downshift-js/downshift#customizing-handlers) but in the item props instead of the input props, and on click and not on key down.

Good luck and let me know if it fixes your scenario.

You can also use `stateReducer` and on `ItemClick` state change remove the selected item from state and pretty much return anything you want. Details [here](https://github.com/downshift-js/downshift#statereducer).
