### ISSUE TITLE
useSelect selectedItem not updated after passing defaultSelectedItem from Redux

### ISSUE THREAD

**Issue by rnnyrk** [downshift-js/downshift#977]
- `downshift` version: 5.0.5

**Relevant code or config**
```javascript
export const Select: React.FC<i.SelectProps> = ({
 items, defaultSelected,
}) => {
  const formMethods = useFormContext();

  console.log({ defaultSelected });

  const {
    isOpen,
    selectedItem,
    getToggleButtonProps,
    getMenuProps,
    highlightedIndex,
    getItemProps,
  } = useSelect({
    items,
    defaultSelectedItem: defaultSelected,
  });

  console.log({ selectedItem });

  return (
     <DownshiftWrapper>
        <input
          type="hidden"
          id={name}
          name={name}
          ref={register}
        />

        <SelectButton
          {...getToggleButtonProps()}
          type="button"
          active={isOpen}
          {...props}
        >
          {selectedItem || <span>Select a item<span>}
        </SelectButton>

        {isOpen && (
          <DropdownList
            {...{ getMenuProps, highlightedIndex, getItemProps, items, variant }}
          />
        )}
      </DownshiftWrapper>
  );
};
```

I'm using the `useSelect` implementation of downshift together with Redux in my stack. I'm fetching the detail of a page and pass that value to my Select box. I pass the defaultValue as `defaultSelected` as soon it's loaded from the server via props.

Although I'm settings the `defaultSelectedItem` and the prop is changing the `selectedItem` isn't updated, see screenshot below of the logs above:
 
<img width="305" alt="Screenshot 2020-03-20 at 15 25 38" src="https://user-images.githubusercontent.com/4519142/77173012-29c07d00-6abf-11ea-8b67-49bb702a60cd.png">

Because the selectedItem is not updated there is no defaultValue, and when I try to update the page the select box has no value.

Any suggestion to what I can do?

**Comment by silviuavram** [comment]
You can use `reset()` once you get a value for `defaultSelected`.
You can use `setSelectedItem()` once you get a value for `defaultSelected`. The difference here is that on next resets you will not have this `selectedItem` anymore, it will reset to `null` which is default value for `selectedItem` reset.
You can fully control the `selectedItem` rather than using `default` prop.

I am guessing `items` are available before `defaultSelected` is available?

If you don't need the item to be available on your future resets, just add to the useEffect `setSelectedItem(defaultSelected)` when it comes as defined from the backend. Or just continue to pass it as `defaultSelectedItem` and on `useEffect` with same condition use `reset()`.

Both reset and setSelectedItem are returned by useSelect. If I think about something better I will get back. Let me know if it works.

**Comment by rnnyrk** [comment]
Thanks for your clear reply. Calling reset on initial `defaultValue` did the trick!

```javascript
  React.useEffect(() => {
    reset();
  }, [defaultSelected]);
```
